# Generated by Django 5.0.6 on 2024-06-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicTacToeRoom',
            new_name='Room',
        ),
    ]
